apiVersion: v1
kind: Template
metadata:
  name: olm-artifacts-template

parameters:
- name: CHANNEL
  value: staging
- name: IMAGE_TAG
  value: latest
- name: OPERATOR_NAME
  value: route-monitor-operator
- name: REGISTRY_IMG
  required: true

objects:
- apiVersion: operators.coreos.com/v1alpha1
  kind: CatalogSource
  metadata:
    name: ${OPERATOR_NAME}-catalog
  spec:
    sourceType: grpc
    image: ${REGISTRY_IMG}:${CHANNEL}-${IMAGE_TAG}
    displayName: ${OPERATOR_NAME} Registry
    publisher: SRE

- apiVersion: operators.coreos.com/v1alpha2
  kind: OperatorGroup
  metadata:
    name: ${OPERATOR_NAME}-og
  spec:
    targetNamespaces:
    - ${OPERATOR_NAME}

- apiVersion: operators.coreos.com/v1alpha1
  kind: Subscription
  metadata:
    name: ${OPERATOR_NAME}
  spec:
    channel: ${CHANNEL}
    name: ${OPERATOR_NAME}
    source: ${OPERATOR_NAME}-catalog
    sourceNamespace: ${OPERATOR_NAME}
